# Generated by Django 5.0 on 2024-03-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='phone_num',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.CharField(default='test', max_length=150),
        ),
    ]
